Update

diff --git a/.github/workflows/nodejs.yml b/.github/workflows/nodejs.yml
--- a/.github/workflows/nodejs.yml
+++ b/.github/workflows/nodejs.yml
@@ -12,7 +12,11 @@ jobs:
 
     steps:
       - name: Cancel if not a release publish # workaround has `on` doesn't have this filter
-        run: exit 1
+        env:
+          ACTION: ${{ github.event.action }}
+        run: |
+          echo "Invalid release action: $ACTION"
+          exit 1
         if: github.event.action != 'published'
       - uses: actions/checkout@v1
       - name: Use Node.js ${{ matrix.node-version }}
